name: flutter_community_challenges
description: A Flutter application to manage community driven Flutter development challenges

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  groovin_material_icons: ^1.0.2
  json_annotation: ^1.0.0
  simple_auth_flutter: ^1.0.6
  firebase_auth: "0.5.18"
  cloud_firestore: "0.7.3"
  google_sign_in: ^3.0.5
  http: ^0.11.3+17
  url_launcher: ^3.0.3

dev_dependencies:
  build_runner: ^0.10.0
  json_serializable: ^1.0.0
  flutter_advanced_networkimage: ^0.3.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/glogo.png
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf